### PR TITLE
Fix long file names causing upload failures for the entire upload batch during migration

### LINKED ISSUE #88: s3migration fails migrating other files if the filename length is greater than 100 chars
lets say i have 3 files in the s3 bucket
1. a.txt
2. b.txt
3. Test0S3MigrationAlternatePart2-Should_not_pass_when_filename_size_is_more_than_100_character.txt

when I start the migration, it fails to migrate all 3 files. 

expected: 

it shouldn't fail migration of other files. It should only fail the migration of the file with name greater than 100 chars

### PR DESCRIPTION
**Pull request by sunilmhta**
Fixing the long file names which cause errors during migration by trimming the long file names to 90 chars.

### CODE REVIEW

File: migration/migrate.go [hunk 1]
```diff
@@ -387,8 +387,23 @@ func (m *Migration) UploadWorker(ctx context.Context, migrator *MigrationWorker)
...
 }
 
+func getShortObjectKey(objectKey string) string {
+	//max length to which objectKey would be trimmed to
+	//reserving 10 chars for duplicate suffixes.
+	const maxLength = 90
+
+	if len(objectKey) > maxLength {
+		//get the last maxLength characters of the object key.
+		shortKey := objectKey[len(objectKey)-maxLength:]
```
Comment (dabasov) [inline migration/migrate.go]: what will happen with duplicates?

Comment (sunilmhta) [reply migration/migrate.go]: There could have been duplicates. Avoiding the duplicates now with hashing.

**Review by Hitenjain14 — APPROVED** [review]
lgtm
